# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'in3-demo-build'

steps:
- script: docker build -f 'IN3.Demo.Api/Dockerfile' -t $(imageName) .
  displayName: 'docker build'
- script: dotnet test IN3.Demo.ApiTest.csproj
